#!/usr/bin/env bash
# ablation_matrix.sh — lattice role-gate ablation MATRIX, bots lane
# (2026-07-24 rev 2).
#
# Lane is now WIRE V5 (deployed 2026-07-24, post-matrix): survival pack
# (hazard-typed last_damage_mod/last_death_mod, hit attribution,
# self_exposure, score_self/score_leader/time_remaining frame) + fight
# decision bias + pipelined collector + fast-nearest spatial lookup.
# Binaries: server-runtime/lithium/game.so and runtime/quake2 rebuilt on
# WSL from the nobara v5 diffs (glibc 2.35 < nobara's 2.38 requirement);
# pre-v5 backups at *.bak-pre-v5-20260724.  Smoke + v5 field probe passed.
#
# Lane-condition change vs the 09:55 launch: the no-opponent lane produced
# ~zero combat for 200k+ transitions/arm (early contact comparable to the
# retired public lane, then visibility/aligned-fire collapsed to zero as the
# self-play policy drifted into down-look — the retired lane was sustained by
# human opponents).  Fix: 3ZB2 scripted opponents, identical across arms.
# Diagnosis details are in the run-log provenance header.
#
# Runs 3 arms SEQUENTIALLY against ONE WSL-local lithium q2ded (loopback
# game port 28300, telemetry 28301) on the fixed generated map
# mllive_44987431 (bundle v2 checksum-verified in all three runtimes).
# Arms:
#   all_on        defaults (all lattice channels live)
#   reward_off    Q2_LATTICE_REWARD=0
#   direction_off --lattice_direction_coef 0
#
# Opponents: BOT_COUNT scripted 3ZB2 bots (default 2 -> botlist ml2sk1;
# 0 disables bots, 1->1v1sk1, 3->2v2sk1, 4->ml4sk1).  4 ML clients + 2 bots
# = 6 players; maxclients 8 keeps the 2 spare engine slots 3ZB2 requires.
# Override with BOT_COUNT in the environment.  The [ml2sk1] section was
# appended to server-runtime/3zb2/3ZBConfig.cfg on 2026-07-24 (two bots
# copied verbatim from [ml4sk1]; backup at 3ZBConfig.cfg.bak-pre-ablation-bots).
#
# Every arm warm-starts from the immutable BC pin
# training-data/resume/ablation_pilot_bc_v2_00049152 (policy + 398-cell
# lattice at step 49,152, optimizer reset) with matched seed 7142026 and the
# deterministic controls required by AGENTS.md
# (--seed N --game_seed N --deterministic 1, Q2_ML_ASYNC=0).
# Horizon: --total_steps 249152, i.e. 200k collected transitions past the
# 49,152-step warm start, per arm (~105 min/arm at ~32 sps, ~5.5h total).
# timelimit 0 / fraglimit 0: single fixed map per arm, no rotation, so the
# map-epoch barrier that stalled the pilot on same-map reload cannot fire.
#
# Usage:
#   ablation_matrix.sh             # all three arms, sequential
#   BOT_COUNT=0 ablation_matrix.sh all_on
#
# The server cfg is (re)generated by this script each run from the sourced
# token (mode 0600).  The token is NEVER printed; the per-arm run log
# records the full Q2_* environment minus *TOKEN* lines.
set -euo pipefail

TREE=/home/raymond/q2-rollout/q2-ml-bot
STAGING=/home/raymond/q2-network-client-staging-20260713
SERVER_ROOT="$STAGING/server-runtime"
CLIENT_ROOT="$STAGING/runtime"
SERVER_CFG=ml_network_local_28300.cfg
GAME_PORT=28300
TELEMETRY_PORT=28301
MAP=mllive_44987431
SEED=7142026
TOTAL_STEPS=249152
BOT_COUNT="${BOT_COUNT:-2}"
# Lane rate switch (2026-07-24 rate ladder, side lane 28320/28321, 4 clients,
# uncontended): 1x=33-34 accepted trans/s clean; 1.5x (15 Hz)=clean but SAME
# 34/s (Python collector ceiling; 768 catchup resyncs vs 82 at 1x); 2x (20 Hz)
# livelocks (0 accepted rounds in 150s; per-round batch compute >50ms tick).
# >1x therefore only skips more game ticks at identical wall-clock throughput.
# Keep 1 unless the collector gets faster; integer rates only.
TIMESCALE="${TIMESCALE:-1}"
case "$TIMESCALE" in
    ''|*[!0-9]*) echo "TIMESCALE must be a positive integer (got $TIMESCALE)" >&2; exit 2 ;;
    0) echo "TIMESCALE must be >= 1" >&2; exit 2 ;;
esac
SIM_HZ=$((10 * TIMESCALE))
CLIENT_FPS=$((15 * TIMESCALE)); [ "$CLIENT_FPS" -lt 60 ] && CLIENT_FPS=60
TOKEN_ENV=/home/raymond/q2-rollout/local-pilot-telemetry.env
RESUME_PIN="$TREE/training-data/resume/ablation_pilot_bc_v2_00049152"
LOG_DIR="$TREE/logs/ablation_matrix"
mkdir -p "$LOG_DIR"

ALL_ARMS=(all_on reward_off direction_off)
if [ "$#" -gt 0 ]; then
    ARMS=("$@")
else
    ARMS=("${ALL_ARMS[@]}")
fi
for arm in "${ARMS[@]}"; do
    case " ${ALL_ARMS[*]} " in
        *" $arm "*) ;;
        *) echo "unknown arm: $arm (valid: ${ALL_ARMS[*]})" >&2; exit 2 ;;
    esac
done

# --- opponents ----------------------------------------------------------------
case "$BOT_COUNT" in
    0) AUTOSPAWN=0; BOTLIST='""';  BOT_DESC="none (pure ML self-play)" ;;
    1) AUTOSPAWN=1; BOTLIST=1v1sk1; BOT_DESC="1 3ZB2 bot (1v1sk1)" ;;
    2) AUTOSPAWN=1; BOTLIST=ml2sk1; BOT_DESC="2 3ZB2 bots (ml2sk1)" ;;
    3) AUTOSPAWN=1; BOTLIST=2v2sk1; BOT_DESC="3 3ZB2 bots (2v2sk1)" ;;
    4) AUTOSPAWN=1; BOTLIST=ml4sk1; BOT_DESC="4 3ZB2 bots (ml4sk1)" ;;
    *) echo "BOT_COUNT must be 0-4 (got $BOT_COUNT)" >&2; exit 2 ;;
esac
if [ "$BOT_COUNT" -gt 4 ]; then
    echo "BOT_COUNT >4 would exceed the maxclients-8 spare-slot rule" >&2
    exit 2
fi

# --- token (mode-checked, never echoed) ---------------------------------------
if [ "$(stat -c '%a' "$TOKEN_ENV")" != "600" ]; then
    echo "refusing to source $TOKEN_ENV: not mode 0600" >&2
    exit 1
fi
source "$TOKEN_ENV"
: "${Q2_ML_CLIENT_TELEMETRY_TOKEN:?token env file missing Q2_ML_CLIENT_TELEMETRY_TOKEN}"
export Q2_ML_CLIENT_TELEMETRY_TOKEN

# --- server cfg (regenerated each run; token-bearing, mode 0600) --------------
write_server_cfg() {
    local path="$SERVER_ROOT/lithium/$SERVER_CFG"
    local old_umask
    old_umask=$(umask)
    umask 077
    cat > "$path" <<EOF
set dedicated 1
set deathmatch 1
set cheats 1
set timelimit 0
set fraglimit 0
set use_mapqueue 0
set mapqueue ""
set map_random 0
set autospawn $AUTOSPAWN
set botlist $BOTLIST
set allow_client_bot_controls 0
set maxclients 8
set ml_enabled 0
set ml_bot_slot 99
set ml_teacher_enabled 0
set ml_client_telemetry 1
set ml_client_telemetry_port $TELEMETRY_PORT
set ml_client_telemetry_token "$Q2_ML_CLIENT_TELEMETRY_TOKEN"
set timedemo $([ "$TIMESCALE" -gt 1 ] && echo 1 || echo 0)
$([ "$TIMESCALE" -gt 1 ] && echo "set cl_maxfps $SIM_HZ")
set timescale 1
set use_runes 1
set use_startobserver 0
set use_startchasecam 0
set use_hook 1
set hook_speed 1900
set hook_pullspeed 1700
set hook_maxtime 15.0
set hook_damage 1
set hook_initdamage 10
set hook_maxdamage 20
set hook_delay 0.2
set rocket_speed_start 650
set rocket_speed_max 2000
set rocket_accel_time 0.75
set rocket_accel_curve 12
set rocket_haste_refire 0.36
set energy_light_speed 1
map $MAP
EOF
    umask "$old_umask"
    chmod 600 "$path"
}
write_server_cfg

# --- server lifecycle (exact PIDs only; no pattern kills) ----------------------
SERVER_PID=""
start_server() {
    local log="$1"
    (cd "$SERVER_ROOT" && exec stdbuf -oL -eL ./q2ded \
        +set game lithium \
        +set dedicated 1 \
        +set ip 127.0.0.1 \
        +set port "$GAME_PORT" \
        +exec "$SERVER_CFG") > "$log" 2>&1 &
    SERVER_PID=$!
    local waited=0
    while [ "$waited" -lt 30 ]; do
        if ! kill -0 "$SERVER_PID" 2>/dev/null; then
            echo "q2ded exited during startup; see $log" >&2
            return 1
        fi
        if grep -q "ML client telemetry: listening on UDP $TELEMETRY_PORT" "$log" 2>/dev/null; then
            return 0
        fi
        sleep 1
        waited=$((waited + 1))
    done
    echo "q2ded did not report telemetry readiness in 30s; see $log" >&2
    return 1
}
stop_server() {
    if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
        kill "$SERVER_PID" 2>/dev/null || true
        wait "$SERVER_PID" 2>/dev/null || true
    fi
    SERVER_PID=""
}
trap stop_server EXIT INT TERM

# --- common trainer environment ------------------------------------------------
export Q2_NETWORK_CLIENTS=4
export Q2_NETWORK_SERVER="127.0.0.1:$GAME_PORT"
export Q2_NETWORK_TELEMETRY_SERVER="127.0.0.1:$TELEMETRY_PORT"
export Q2_NETWORK_CLIENT_BINARY="$CLIENT_ROOT/quake2"
export Q2_NETWORK_CLIENT_ROOT="$CLIENT_ROOT"
export Q2_NETWORK_CLIENT_DATA_ROOT="$STAGING/client-data/ablation_matrix"
export Q2_NETWORK_HARNESS_PORT_BASE=39000
export Q2_NETWORK_QPORT_BASE=49000
export Q2_NETWORK_CLIENT_TIMEOUT=60
export Q2_NETWORK_ROUND_TIMEOUT=3
export Q2_NETWORK_MAX_REJECTED_ECHOES=16
export Q2_NETWORK_CLIENT_ID_PREFIX=ablation-matrix
export Q2_EXT_OBS=1
export Q2_RESUME_DIR="$RESUME_PIN"
export Q2_RUNS_DIR="$TREE/training-data/runs"
export Q2_LATTICE_DIR=/home/raymond/q2-rollout/runtime/baseq2/maps
export Q2_RUST_LATTICE=1
export Q2_RUST_EXTENSION_PATH=/home/raymond/q2-rollout/python/q2_lattice_rs.so
export Q2_POLICY_STATEFUL=1
export Q2_ML_ASYNC=0
if [ "$TIMESCALE" -gt 1 ]; then
    # Headless clients must pump faster than the accelerated sim.
    export Q2_NETWORK_CLIENT_EXTRA_ARGS="+set cl_maxfps $CLIENT_FPS"
fi
export LD_LIBRARY_PATH="$CLIENT_ROOT/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH=/home/raymond/q2-rollout/python${PYTHONPATH:+:$PYTHONPATH}

run_arm() {
    local arm="$1"
    local run_tag="ablation_matrix_$arm"
    local ckpt_dir="$TREE/training-data/checkpoints/$run_tag"
    local arm_log="$LOG_DIR/$run_tag.log"
    local server_log="$LOG_DIR/${run_tag}_server.log"
    mkdir -p "$ckpt_dir"

    # Per-arm ablation switches.
    local extra_env=()
    local direction_coef=0.02
    case "$arm" in
        all_on)        ;;
        reward_off)    extra_env+=(Q2_LATTICE_REWARD=0) ;;
        direction_off) direction_coef=0 ;;
    esac

    # Fresh server per arm: identical initial map state for every arm.
    stop_server
    start_server "$server_log"

    {
        echo "=== $run_tag ==="
        echo "date: $(date -Is)"
        echo "arm: $arm  seed: $SEED  warm_start: $RESUME_PIN (step 49152, reset_optimizer 1)"
        echo "horizon: total_steps=$TOTAL_STEPS (200k collected transitions past warm start)"
        echo "server: 127.0.0.1:$GAME_PORT telemetry=127.0.0.1:$TELEMETRY_PORT map=$MAP cfg=$SERVER_CFG timelimit=0 fraglimit=0"
        echo "lane rate: ${TIMESCALE}x (sim ${SIM_HZ} Hz; timedemo+cl_maxfps server-side, cl_maxfps $CLIENT_FPS client-side)"
        echo "lane-condition rev2 (2026-07-24): opponents=$BOT_DESC; prior no-bot lane produced ~zero combat"
        echo "  (visibility/aligned-fire collapsed to 0 under self-play drift; retired public lane was"
        echo "   human-sustained).  cfg delta vs rev1: autospawn 0->${AUTOSPAWN}, botlist \"\"->${BOTLIST}."
        echo "  contact pre-verified on identical cfg: hit events + kill events nonzero within 11,264"
        echo "  transitions (run ppo_ablation_verify_bots_1784920351)."
        echo "--- environment (secrets redacted) ---"
        printenv | grep -E '^(Q2_|LD_LIBRARY_PATH=|PYTHONPATH=)' | grep -v 'TOKEN' | sort
        echo "BOT_COUNT=$BOT_COUNT"
        echo "--- command ---"
        echo "python3 -u -m train.ppo --n_servers 1 --n_bots_per_server 4 --n_ml_bots 4" \
             "--n_steps 128 --n_epochs 2 --batch_size 512 --chunk_len 16" \
             "--total_steps $TOTAL_STEPS --lr 1e-5 --clip_eps 0.2 --vf_coef 0.1" \
             "--ent_coef 0.005 --max_grad_norm 0.5 --aux_coef 0.01" \
             "--aim_anchor_coef 0.02 --lattice_direction_coef $direction_coef" \
             "--map_name $MAP --map_change_episodes 0 --max_ep_steps 1000" \
             "--timelimit 0 --fraglimit 0 --timescale $TIMESCALE --save_every 8192" \
             "--seed $SEED --game_seed $SEED --deterministic 1" \
             "--reset_optimizer 1 --resume"
        echo "--- trainer output ---"
    } >> "$arm_log"

    (
        cd "$TREE"
        env "${extra_env[@]}" \
            Q2_RUN_TAG="$run_tag" \
            Q2_CKPT_DIR="$ckpt_dir" \
            python3 -u -m train.ppo \
                --n_servers 1 --n_bots_per_server 4 --n_ml_bots 4 \
                --n_steps 128 --n_epochs 2 --batch_size 512 --chunk_len 16 \
                --total_steps "$TOTAL_STEPS" --lr 1e-5 --clip_eps 0.2 \
                --vf_coef 0.1 --ent_coef 0.005 --max_grad_norm 0.5 \
                --aux_coef 0.01 --aim_anchor_coef 0.02 \
                --lattice_direction_coef "$direction_coef" \
                --map_name "$MAP" --map_change_episodes 0 --max_ep_steps 1000 \
                --timelimit 0 --fraglimit 0 --timescale "$TIMESCALE" --save_every 8192 \
                --seed "$SEED" --game_seed "$SEED" --deterministic 1 \
                --reset_optimizer 1 --resume
    ) >> "$arm_log" 2>&1
    echo "=== $run_tag finished: $(date -Is) ===" >> "$arm_log"
}

for arm in "${ARMS[@]}"; do
    echo "[ablation_matrix] starting arm: $arm (opponents: $BOT_DESC)"
    run_arm "$arm"
    echo "[ablation_matrix] arm complete: $arm"
done
stop_server
trap - EXIT INT TERM
echo "[ablation_matrix] all requested arms complete"
